# C compiler and flags

CC = gcc
CFLAGS = -std=c17 -Wall -Werror -pedantic

# Targets

# TODO: Dummy target. Edit so it satisfies the requirements.


Life: main.c life.c 
	${CC} ${CFLAGS} -o $@ $^

clean:
	rm -f *.o
	rm -f Life